import React from "react";
import "./LegalPages.css";

const TermsOfService: React.FC = () => {
  return (
    <div className="legal-page-content">
      <div className="legal-container">
        <h1>Terms & Conditions</h1>

        <p>
          Welcome to Fitness Tracker! These Terms and Conditions ("Terms")
          govern your use of the Fitness Tracker website and mobile application
          (collectively, the "Service") operated by Sarmilan Sreekaran ("us",
          "we", or "our").
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using our Service, you agree to be bound by these
          Terms. If you disagree with any part of the terms, you may not access
          the Service.
        </p>

        <h2>2. Use License</h2>
        <p>
          Permission is granted to temporarily access our Service for personal,
          non-commercial use only. This is the grant of a license, not a
          transfer of title, and under this license you may not:
        </p>
        <ul>
          <li>Modify or copy the materials</li>
          <li>Use the materials for any commercial purpose</li>
          <li>
            Attempt to reverse engineer any software contained on our Service
          </li>
          <li>
            Remove any copyright or other proprietary notations from the
            materials
          </li>
        </ul>

        <h2>3. User Accounts</h2>
        <p>
          When you create an account with us, you must provide accurate and
          complete information. You are responsible for maintaining the
          confidentiality of your account and password.
        </p>

        <h2>4. Health Disclaimer</h2>
        <p>
          The Service is not intended to provide medical advice, diagnosis, or
          treatment. Always seek the advice of your physician or other qualified
          health provider with any questions you may have regarding a medical
          condition.
        </p>

        <h2>5. Third-Party Services</h2>
        <p>
          Our Service may contain links to third-party web sites or services
          that are not owned or controlled by us. We have no control over, and
          assume no responsibility for, the content, privacy policies, or
          practices of any third-party web sites or services.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          In no event shall we be liable for any damages arising out of the use
          or inability to use the materials on our Service, even if we have been
          notified orally or in writing of the possibility of such damage.
        </p>

        <h2>7. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. We will
          provide notice of any changes by posting the new Terms on this page
          and updating the "effective date" at the bottom of these Terms.
        </p>

        <h2>8. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the
          laws of Canada, without regard to its conflict of law provisions.
        </p>

        <h2>9. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at
          fitness.tracker.00001@gmail.com.
        </p>

        <p className="last-updated">
          These terms are effective as of 2025-08-27
        </p>

        <hr />

        <p>
          This Terms and Conditions page was generated by{" "}
          <a
            href="https://app-privacy-policy-generator.nisrulz.com/"
            target="_blank"
            rel="noopener noreferrer"
          >
            App Privacy Policy Generator
          </a>
        </p>
      </div>
    </div>
  );
};

export default TermsOfService;
